-- Reference data exported from the legacy production database on 2026-08-26.
--
-- routes / boats / seasons / times are slow-moving and belong in version control. The day overrides
-- are a point-in-time snapshot: ops toggles them from the Programs calendar, so this file drifts the
-- moment anyone does. It seeds an empty database; keeping it in step afterwards needs a sync path.
--
-- Values are ON CONFLICT DO NOTHING so re-seeding never clobbers edits made through this service.
--
-- Deliberately excluded:
--   * boat b1787213821911 ("เรือปลอม", fake boat) — test data in production, zero references
--   * boats.totalcap — it is license_pax + crew, not a passenger capacity
--   * routes.code (empty on all 14) and routes.mealvenueid (out of scope)
--   * sb_weather — operational cancellations, not catalogue

INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r2', 'Early Tiger Similan Islands', 'tublamu', 'similan', '#378ADD', 'เกาะ 5,6,7,8,9', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r3', 'Similan Islands - PG', 'tublamu', 'similan', '#185fa5', 'เกาะ 5,6,7,8,9', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r4', 'Similan Islands by Catamaran', 'tublamu', 'similan', '#4a90d9', 'เกาะ 5,6,7,8,9', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r5', 'Similan Islands by Speedboat', 'tublamu', 'similan', '#6aaee0', 'เกาะ 5,6,7,8,9', 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r6', 'Surin Islands by Speedboat', 'tublamu', 'surin', '#3B6D11', 'เกาะสุรินทร์เหนือ-ใต้', 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r1784542898734', 'Day Trip - Se La Va', 'ranong', 'selava', '#BA7517', 'เกาะเซลาวา', 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r1784882390130', 'Day Trip - Nyaung Oo Phee Island', 'ranong', 'nyaung', '#0F6E56', 'เกาะนาวโอพี', 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r1', 'Early Tratato Similan Islands', 'tublamu', 'similan', '#1a7fa0', 'เกาะ 5,6,7,8,9', 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r11', 'Early Krabi + Phang Nga', 'panwa', 'krabi', '#0F6E56', 'เกาะห้องกระบี่, เกาะปันหยี, อ่าวพังงา', 8) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r7', 'Early OTA Phi Phi Bamboo', 'panwa', 'phiphi', '#c0392b', 'เกาะพีพี, ไม้ไผ่', 9) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r8', 'Early SY Phi Phi Bamboo', 'panwa', 'phiphi', '#e74c3c', 'เกาะพีพี, ไม้ไผ่', 10) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r9', 'Phi Phi Bamboo - FS', 'panwa', 'phiphi', '#e85d5d', 'เกาะพีพี, ไม้ไผ่', 11) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r10', 'Phi Phi Bamboo by Speedboat', 'panwa', 'phiphi', '#ff9999', 'เกาะพีพี, ไม้ไผ่', 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, pier, family_id, color, islands, sort) VALUES ('r12', 'Whale Shark Phi Phi Maiton Sunset', 'panwa', 'whaleshark', '#BA7517', 'เกาะพีพี เกาะไม้ท่อน ชมพระอาทิตย์ตก', 13) ON CONFLICT (id) DO NOTHING;

INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b1', 'Aluminous1', 'Catamaran', 'tublamu', 64, 75, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b10', 'Aluminous2', 'Catamaran', 'panwa', 44, 75, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b11', 'Achilles', 'Speedboat', 'panwa', 65, 75, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b12', 'Hermetis', 'Speedboat', 'panwa', 65, 75, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b13', 'Oceanus', 'Speedboat', 'panwa', 38, 45, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b14', 'Juliet', 'Speedboat', 'panwa', 34, 45, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b15', 'Rolanda', 'Speedboat', 'panwa', 38, 47, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b1784877193883', 'Tri Star 01', 'Speedboat', 'ranong', 38, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b1787213855690', 'Tri Star 02', 'Speedboat', 'ranong', 38, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b2', 'Artemis', 'Speedboat', 'tublamu', 65, 75, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b3', 'Okeanos', 'Speedboat', 'tublamu', 56, 75, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b4', 'Irena', 'Speedboat', 'panwa', 56, 70, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b5', 'Andaman Ryder', 'Speedboat', 'panwa', 56, 70, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b6', 'Zeus', 'Speedboat', 'tublamu', 40, 47, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b7', 'Verona', 'Speedboat', 'tublamu', 34, 45, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b8', 'Tadeo', 'Speedboat', 'tublamu', 38, 47, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO boats (id, name, type, pier, capacity, license_pax, crew) VALUES ('b9', 'Romeo', 'Speedboat', 'tublamu', 34, 45, 3) ON CONFLICT (id) DO NOTHING;

INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss1', 'r1', 'open', '2025-10-15', '2026-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss2', 'r1', 'closed', '2026-05-16', '2026-10-14') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss3', 'r1', 'open', '2026-10-15', '2027-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss22', 'r10', 'open', '2026-01-01', '2026-12-31') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss23', 'r11', 'open', '2026-01-01', '2026-12-31') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss24', 'r12', 'open', '2025-10-15', '2026-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('s1779769976538', 'r12', 'open', '2026-05-16', '2026-09-30') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss26', 'r12', 'open', '2026-10-15', '2027-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('s1784546015855', 'r1784542898734', 'open', '2026-11-01', '2027-04-30') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('s1784882417568', 'r1784882390130', 'open', '2026-11-01', '2027-04-30') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss4', 'r2', 'open', '2025-10-15', '2026-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss5', 'r2', 'closed', '2026-05-16', '2026-10-14') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss6', 'r2', 'open', '2026-10-15', '2027-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss7', 'r3', 'open', '2025-10-15', '2026-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss8', 'r3', 'closed', '2026-05-16', '2026-10-14') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss9', 'r3', 'open', '2026-10-15', '2027-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss10', 'r4', 'open', '2025-10-15', '2026-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss11', 'r4', 'closed', '2026-05-16', '2026-10-14') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss12', 'r4', 'open', '2026-10-15', '2027-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss13', 'r5', 'open', '2025-10-15', '2026-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss14', 'r5', 'closed', '2026-05-16', '2026-10-14') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss15', 'r5', 'open', '2026-10-15', '2027-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss16', 'r6', 'open', '2025-10-15', '2026-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss17', 'r6', 'closed', '2026-05-16', '2026-10-14') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss18', 'r6', 'open', '2026-10-15', '2027-05-15') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss19', 'r7', 'open', '2026-01-01', '2026-12-31') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss20', 'r8', 'open', '2026-01-01', '2026-12-31') ON CONFLICT (id) DO NOTHING;
INSERT INTO route_seasons (id, route_id, kind, from_date, to_date) VALUES ('ss21', 'r9', 'open', '2026-01-01', '2026-12-31') ON CONFLICT (id) DO NOTHING;

INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r1', 0, '05:30') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r10', 0, '09:00') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r11', 0, '06:30') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r12', 0, '10:00') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r1784542898734', 0, '08:00') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r1784882390130', 0, '08:00') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r2', 0, '07:00') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r3', 0, '08:00') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r4', 0, '08:30') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r5', 0, '08:30') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r6', 0, '08:00') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r7', 0, '06:30') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r8', 0, '06:30') ON CONFLICT (route_id, idx) DO NOTHING;
INSERT INTO route_times (route_id, idx, departs_at) VALUES ('r9', 0, '07:00') ON CONFLICT (route_id, idx) DO NOTHING;

INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-01', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-03', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-04', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-05', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-06', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-07', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-08', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-10', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-11', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-12', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-13', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-14', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-15', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-17', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-18', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-19', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-20', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-21', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-22', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-24', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-25', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-26', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-27', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-28', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-06-29', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-01', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-02', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-03', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-04', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-05', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-06', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-08', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-09', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-10', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-11', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-12', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-13', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-15', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-16', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-17', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-18', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-19', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-20', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-22', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-23', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-24', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-25', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-26', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-27', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-29', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-30', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-07-31', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-01', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-02', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-03', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-05', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-06', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-07', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-08', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-09', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-10', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-12', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-13', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-14', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-15', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-16', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-17', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-19', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-20', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-21', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-22', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-24', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-26', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-27', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-28', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-29', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r11', '2026-08-31', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-05-30', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-05-31', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-04', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-08', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-09', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-11', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-13', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-16', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-18', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-20', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-22', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-23', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-25', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-27', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-06-29', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-07-01', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-07-03', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-07-06', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-07-09', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-07-11', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-07-16', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-07-20', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-07-23', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-07-25', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-07-27', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-08-01', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-08-03', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-08-06', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-08-13', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-08-17', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-08-24', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-08-31', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-09-07', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-09-14', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-09-21', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-09-28', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-01', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-02', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-03', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-04', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-05', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-06', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-07', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-08', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-09', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-10', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-11', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-12', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-13', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r12', '2026-10-14', 'open') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-05-30', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-05-31', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-01', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-02', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-04', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-05', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-06', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-07', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-08', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-09', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-11', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-12', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-13', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-14', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-15', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-16', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-18', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-19', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-20', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-21', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-22', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-23', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-25', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-26', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-27', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-28', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-29', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-06-30', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-02', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-03', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-04', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-05', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-06', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-07', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-09', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-10', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-11', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-12', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-13', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-14', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-16', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-17', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-18', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-19', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-20', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-21', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-23', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-24', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-25', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-26', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-27', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-28', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-30', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r7', '2026-07-31', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-01', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-03', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-04', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-06', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-07', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-08', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-10', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-11', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-12', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-13', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-14', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-15', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-17', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-18', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-20', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-21', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-22', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-24', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-25', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-27', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-28', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-06-29', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-01', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-02', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-04', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-05', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-06', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-08', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-09', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-11', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-12', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-13', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-15', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-16', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-18', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-19', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-20', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-22', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-23', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-25', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-26', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-27', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-29', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r8', '2026-07-30', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-01', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-02', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-04', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-05', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-06', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-08', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-09', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-11', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-12', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-13', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-14', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-15', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-16', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-18', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-19', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-20', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-22', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-23', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-25', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-26', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-27', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-29', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-06-30', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-02', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-03', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-04', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-06', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-07', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-09', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-10', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-11', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-13', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-14', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-16', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-17', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-18', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-20', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-21', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-23', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-24', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-25', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-27', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-28', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-30', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;
INSERT INTO route_day_overrides (route_id, service_date, kind) VALUES ('r9', '2026-07-31', 'closed') ON CONFLICT (route_id, service_date) DO NOTHING;

INSERT INTO boat_capacity_overrides (boat_id, service_date, capacity, reason) VALUES ('b10', '2026-07-26', 47, 'เกิน 1 INF') ON CONFLICT (boat_id, service_date) DO NOTHING;
INSERT INTO boat_capacity_overrides (boat_id, service_date, capacity, reason) VALUES ('b10', '2026-08-04', 46, 'TEST') ON CONFLICT (boat_id, service_date) DO NOTHING;
